from typing import Any, Optional

class Serial:
    def __init__(self, port: str, baudrate: int = ..., timeout: Optional[float] = ...) -> None: ...
    def write(self, data: bytes) -> int: ...
    def flush(self) -> None: ...
    def close(self) -> None: ...
    def __enter__(self) -> "Serial": ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None: ...

class SerialException(Exception): ...
